apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-hello-world
spec:
  selector:
    matchLabels:
      host: bar
  replicas: 3
  template:
    metadata:
      labels:
        host: bar
    spec:
      containers:
      - name: hello-app-2
        image: "us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0"
        env:
        - name: "PORT"
          value: "8080"
