apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-hello-world
spec:
  selector:
    matchLabels:
      host: foo
  replicas: 2
  template:
    metadata:
      labels:
        host: foo
    spec:
      containers:
      - name: hello-app-1
        image: "us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0"
        env:
        - name: "PORT"
          value: "8080"
