apiVersion: v1
kind: Service
metadata:
  name: bar-hello-world
  annotations:
    cloud.google.com/neg: '{"ingress": false}'
spec:
  type: NodePort
  selector:
    host: bar
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
