apiVersion: v1
kind: Service
metadata:
  name: hello-world-2
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"session-cookie-config"}}'
spec:
  type: ClusterIP
  selector:
    greeting: hello
    version: two
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
